### ISSUE TITLE
question: ability to disable template rendering

### ISSUE THREAD

**Issue by charliie-dev** [blurgyy/dt#18]
Some of my file doesn't comply with `Handlebars` syntax.
Is it possible to add a local setting that can just symlink/copy the file over to `target`?
Or is there other way around?

`linux.toml`:
![圖片](https://github.com/blurgyy/dt/assets/32497323/aa437210-9709-4dfb-b806-e194d26844f3)

error log:
![圖片](https://github.com/blurgyy/dt/assets/32497323/473b046c-b08b-4192-8173-355ffd45ef94)

`lfrc:L34`:
https://github.com/CharlesChiuGit/dotfiles/blob/077960d9e2c7bc75813fe792964731aeb03874e3/cli-utils/lf/lfrc#L34

**Comment by blurgyy** [comment]
Hi @CharlesChiuGit,

Thank you for opening an issue!

`dt-cli` supports this with a config option `renderable` which defaults to `true`.  To avoid rendering a source file, you can add `renderable = false` for the group that you want to to skip template rendering, or add the `renderable = false` line under `[global]` to disable templating globally.  This has been mentioned in the documentation [here](https://dt.cli.rs/features/04-templating.html).  E.g.

```toml
# this is a config file for dt-cli
[global]
# renderable = false  # globally disables templating

[[local]]
name = "lf"
base = "/some/path"
sources = [ "lfrc", "and", "some", "other", "files" ]
target = "/some/other/path"
# renderable = false  # disables templating only for this group
```

Another solution (more of a workaround) is to escape the handlebars inside the source file itself by adding a backslash before the opening "handlebar".  With this workaround, `dt-cli`'s config file does not need to be modified.  E.g.:

```diff
-cmd open ${{
+cmd open $\{{
     test -L $f && f=$(readlink -f $f)
     case $(file --mime-type $f -b) in
         text/*) $EDITOR $fx;;
         *) for f in $fx; do setsid $OPENER $f > /dev/null 2> /dev/null & done;;
     esac
 }}
```

I recommend you to refer to the [Key References](https://dt.cli.rs/config/key-references.html) section in the documentation while creating a config file for `dt-cli`, but feel free to let me know if any problem arises.

Cheers!
